services:
  ros1-noetic:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros1
    container_name: axon_ros1
    volumes:
      - ../data:/data
      - ../config:/workspace/config
    environment:
      - ROS_DISTRO=noetic
      - ROS_VERSION=1
    network_mode: host
    command: /bin/bash

  ros2-humble:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros2.humble
    container_name: axon_ros2_humble
    volumes:
      - ../data:/data
      - ../config:/workspace/config
    environment:
      - ROS_DISTRO=humble
      - ROS_VERSION=2
    network_mode: host
    command: /bin/bash

  ros2-jazzy:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros2.jazzy
    container_name: axon_ros2_jazzy
    volumes:
      - ../data:/data
      - ../config:/workspace/config
    environment:
      - ROS_DISTRO=jazzy
      - ROS_VERSION=2
    network_mode: host
    command: /bin/bash

  ros2-rolling:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros2.rolling
    container_name: axon_ros2_rolling
    volumes:
      - ../data:/data
      - ../config:/workspace/config
    environment:
      - ROS_DISTRO=rolling
      - ROS_VERSION=2
    network_mode: host
    command: /bin/bash

