# Message type to Arrow schema mappings
# This file documents the schema conversion for common ROS message types

sensor_msgs/Image:
  fields:
    - name: "header"
      type: "struct"
      fields:
        - name: "seq"
          type: "uint32"
        - name: "stamp"
          type: "struct"
          fields:
            - name: "sec"
              type: "int32"
            - name: "nsec"
              type: "uint32"
        - name: "frame_id"
          type: "string"
    - name: "height"
      type: "uint32"
    - name: "width"
      type: "uint32"
    - name: "encoding"
      type: "string"
    - name: "is_bigendian"
      type: "bool"
    - name: "step"
      type: "uint32"
    - name: "data"
      type: "binary"

sensor_msgs/PointCloud2:
  fields:
    - name: "header"
      type: "struct"
    - name: "height"
      type: "uint32"
    - name: "width"
      type: "uint32"
    - name: "fields"
      type: "list"
    - name: "is_bigendian"
      type: "bool"
    - name: "point_step"
      type: "uint32"
    - name: "row_step"
      type: "uint32"
    - name: "data"
      type: "binary"
    - name: "is_dense"
      type: "bool"

nav_msgs/Odometry:
  fields:
    - name: "header"
      type: "struct"
    - name: "child_frame_id"
      type: "string"
    - name: "pose"
      type: "struct"
    - name: "twist"
      type: "struct"

std_msgs/String:
  fields:
    - name: "data"
      type: "string"

std_msgs/Int32:
  fields:
    - name: "data"
      type: "int32"

std_msgs/Float64:
  fields:
    - name: "data"
      type: "float64"

